version: "3"
services:

  php:
    image: php:8.2-fpm
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    ports :
      - "9000:9000"
    volumes:
      - ./src:/home/homepage/blog/src/public
      - ./src/public:/home/homepage/blog/src/public

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/home/homepage/blog/src/public
      - ./src/public:/home/homepage/blog/src/public
      - ./nginx.conf:/etc/nginx/nginx.conf

  mariadb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file: ./mysql/.env

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 13000
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "13000:13000"