version: "3"
services:

  php:
    image: php:8.2-fpm
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    ports :
      - "9000:9000"
    volumes:
      - ./:/home/blog
      - ./public:/home/blog/public

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/home/blog
      - ./public:/home/blog/public
      - ./nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - TZ=Asia/Seoul
    restart: always
    volumes:
      - ./opt/lib/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=FALSE

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 13000
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "13000:13000"
